### ISSUE TITLE
All mock proposals showing in /ultradash

### ISSUE THREAD

**Issue by tnewkirk** [gundotio/PublicBugs#1]
(I believe) regardless of whether or not new developers check/uncheck the 'apply to this gig for real' box during the mock proposal part of their registration, all the proposals are showing up in /ultradash.  (I've had developers say they're positive they did NOT check the real box initially).

I can see whether the proposal is real or not by finding the external proposal in /admin (/admin -> contract job xxx -> 'delete' -> external proposals) and seeing if the 'real' box is checked, but obviously thats not ideal.

Thanks R!

**Comment by Miserlou** [comment]
fixed
