### ISSUE TITLE
Adding emails to MC lists

### ISSUE THREAD

**Issue by tyenamandra** [gundotio/PublicBugs#10]
In Connextra format:

As someone who's helping Gun.io grow, I need an easy way to add the emails of all (1) current developers and (2) current employers to separate MailChimp lists to send them information about recent blog posts, product releases, and general announcements

**Comment by Miserlou** [comment]
Is this not already the case? None of the dev signups go onto MC, they're kept internal except when moved to CM.

**Comment by tyenamandra** [comment]
I think it would be strategic to consolidate our email assets and use one service provider. What's the current way to download all users, all hackers, all employers? I don't have the documentation but would like to show Jake how to do it!

Thanks!

**Comment by Miserlou** [comment]
This needs to be done manually for now. Can add hackers automatically during hacker onboarding reworking in late March.
