### ISSUE TITLE
Asking where leads came from

### ISSUE THREAD

**Issue by tyenamandra** [gundotio/PublicBugs#11]
As a steward of Gun.io's growth, it would be nice to see where leads come from by asking them 'How did you hear about us?' in the sign-up flow

**Comment by Miserlou** [comment]
Still waiting on feedback on what the fields should be.

**Comment by tyenamandra** [comment]
We can wait on Jake's input, but I was doing some reading, and apparently 'Who referred you to us?' with a blank field as an answer is way more pointed, plus implies that referral is not only possible, but a commonly occurring behavior. It's also natural to answer the question with, "Google Search" or "Found via XXX's blog."

**Comment by Miserlou** [comment]
Okay, made it a blank text field.
