### ISSUE TITLE
Migrate e-mail list to Mailchimp

### ISSUE THREAD

**Issue by JakeJorgovan** [gundotio/PublicBugs#13]
Rich, can you migrate the e-mail list from the internal database to Mailchimp with the following segmentation:

- Employers who have hired from you in the past
- Developers who are signed up for the weekly digest 

Can you do this by Wednesday so I can send out a digest on Thursday?

**Comment by Miserlou** [comment]
Devs now in MC, need to clarify on employers. PM me on slack.
