### ISSUE TITLE
dev profile 404

### ISSUE THREAD

**Issue by libbyroyer** [gundotio/PublicBugs#15]
gun.io/accounts/AndreLion

**Comment by libbyroyer** [comment]
https://gun.io/accounts/GabeMedrash/

**Comment by libbyroyer** [comment]
https://gun.io/accounts/theDrake

**Comment by tyenamandra** [comment]
Seconded

**Comment by Miserlou** [comment]
Major regex bug, fixed in source.

**Comment by libbyroyer** [comment]
https://gun.io/accounts/AndreLion
