### ISSUE TITLE
Getting some spammy paid_leads...

### ISSUE THREAD

**Issue by tnewkirk** [gundotio/PublicBugs#16]
Some spammers are starting to get in the front. Maybe need to up the anti-spam up a notch.

**Comment by Miserlou** [comment]
This still happening?

**Comment by tnewkirk** [comment]
Yep

**Comment by Miserlou** [comment]
Shit. Okay.

**Comment by Miserlou** [comment]
Okay, a few more antispam measures in place. Fingers crossed. LMK if they don't work.
