### ISSUE TITLE
Report Submitted from User: 404 message

### ISSUE THREAD

**Issue by tyenamandra** [gundotio/PublicBugs#18]
Patrick Altman
7:15 PM (1 minute ago)

https://www.dropbox.com/s/wvr1fyaw9i6u3m6/Screenshot%202015-02-17%2019.13.48.png?dl=0

Just tried posting a new listing for $24k and after a few minutes, I got this nginx error.
Not sure if it went through or not. I basically need another 2 listings like my previous $24k listings — 2 devs for 3-months deals. Can you make that happen for me?

Thanks,
Patrick

**Comment by tyenamandra** [comment]
(additional info: We still 'received' the leads as hot-ish leads)

**Comment by Miserlou** [comment]
Hard to fix without knowing what the URL is. :(
