### ISSUE TITLE
typo in email sent to developers :)

### ISSUE THREAD

**Issue by tyenamandra** [gundotio/PublicBugs#19]
We had 'fit' as 'fir'

Hello, XXX,

We're sorry, but the gig "JavaScript developer needed for file uploading app" has been awarded to another developer.

Please don't be discouraged! We thought your proposal was really good, and certainly better than many of the other proposals submitted, however it appears that there was a better fit for this job.

We encourage you to keep at it! With your skills, you should be able to land a good gig shortly.

Thanks for applying!,

Team Gun.io
(650) 966-7660

**Comment by Miserlou** [comment]
Fixed. We need a dedicated copy checker.
