### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by tyenamandra** [gundotio/PublicBugs#20]
PM me if concerns w/ any below:

### Thematic details to include

* We get it how we live: we're a nationally distributed remote team

### Who's on team?
Libby Royer - Community
Richard Jones - CTO/Founder
Tyler Newkirk - Community
Teja Yenamandra - CEO
Jake Jorgovan - Growth
JohnPaul Bennett - CFO
David Head - Designer

^^
Need to keep title bloat to a minimum on community-facing pages...

### Adding new photos
Might need to circle up with Team on Monday to get the HQ photo assets

**Comment by Miserlou** [comment]
Photos and bios still needed.
