### ISSUE TITLE
Allowing employers AND developers to edit jobs

### ISSUE THREAD

**Issue by tyenamandra** [gundotio/PublicBugs#23]
Just a thought, but, what if we allow employers and developers to edit jobs that are posted in a 'pull request' kind of way? I think we can do this in a cool way.

Some thoughts:
1. Doing it in a way that provides negotiating leverage to developers
2. If the written spec/estimate on the site fully reflects post-introduction job details, I assume we'll get more payments compliance
3. Once introduced, allowing employers to publicly answer questions about their job in a way that helps all approved developers get more intelligence / clarity on the job
4. Maybe before even introduced, there's a way for employers to add extra details themselves as comments?

**Comment by Miserlou** [comment]
Not doing this.

**Comment by tyenamandra** [comment]
yea, not relevant anymore
