### ISSUE TITLE
Not able to submit a proposal when using search function

### ISSUE THREAD

**Issue by libbyroyer** [gundotio/PublicBugs#25]
Got this email from a developer:

"I have another suggestion to make; so I have just discovered the search functionality and when using it I 
noticed that while it does filter the gigs appropriately, it does not allow to submit the proposal when expanding the
gig item; it just allows you to 'show more information'. I  don't know if that's the way its intended but in my 
opinion its a bit strange because now that you have found a gig that matches your search you have to go back
to the full listing in order to submit a proposal....kinda defeats the purpose of the search. It would be great if one 
is able to submit the proposal in the search results page."

**Comment by Miserlou** [comment]
Pressing 'Show More Information' brings up the proposal box.

Changed to 'Show more information and application..'
