### ISSUE TITLE
Dossier delivery issue

### ISSUE THREAD

**Issue by tnewkirk** [gundotio/PublicBugs#26]
- not sure if dossier's are being sent when triggered

- last few times they haven't shown up in inbox like usual, and last employer notified that they never received it

- candidates do show up in employer dash however

**Comment by tyenamandra** [comment]
dossiers going into spam

**Comment by Miserlou** [comment]
Not fixed but will report errors better now

**Comment by Miserlou** [comment]
Still happening?

**Comment by tnewkirk** [comment]
dossiers working now
