### ISSUE TITLE
Employer gets error when trying to hire a candidate

### ISSUE THREAD

**Issue by tyenamandra** [gundotio/PublicBugs#27]
Please see attached image, thanks!

![screen shot 2015-03-02 at 10 51 55 pm](https://cloud.githubusercontent.com/assets/2800868/6456747/be43786e-c12e-11e4-84a4-5bf3edaa0d3d.png)

PM me for user details

**Comment by tnewkirk** [comment]
seconded - this has been occurring in last handful of cases.

**Comment by Miserlou** [comment]
Still happening?
