### ISSUE TITLE
404 error message when client tries to contact a dev

### ISSUE THREAD

**Issue by libbyroyer** [gundotio/PublicBugs#32]
https://gun.io/conversation/Cole Hawkins/

client is unable to read message, maybe because there is a space in this developers username? I've never seen that.

**Comment by Miserlou** [comment]
Yeah that's almost certainly it. Thanks.

**Comment by Miserlou** [comment]
So this guy just shouldn't have a space in his name, that's the real solution here. Not sure how that could have happened in the first place.
