### ISSUE TITLE
Change initial Tyler email copy as per Jake's request

### ISSUE THREAD

**Issue by tyenamandra** [gundotio/PublicBugs#34]
Change to:

Hey there,

Thanks for submitting your project through Gun.io. My name is Tyler Newkirk and it’s my job to make sure your project is a massive success.

I have already received your initial project description! However, it would be great to hop on a call with you to discuss your needs in more detail. 

If you haven’t already please use this link to schedule a call with me: https://www.timetrade.com/book/RLGP2

If you have any questions in the meantime, feel free to reply to this e-mail or give us a call. Either myself or one of my team members will get back to you as soon as we possibly can.

Thanks for choosing Gun.io. I look forward to helping you hire elite developers for your opportunity!

[sig]

**Comment by Miserlou** [comment]
Discuss on Slack first please
