### ISSUE TITLE
Few default changes for Close..

### ISSUE THREAD

**Issue by tnewkirk** [gundotio/PublicBugs#7]
1. Set default "confidence rate" for any new/incoming paid leads to 50% (with status at 'needs more info', i.e. see below)

2. Make the default 'status' for the auto created opportunities "needs more info" instead of "needs credit card'

3. Set the default 'estimated close date' to the date that the paid lead is submitted, if possible

**Comment by Miserlou** [comment]
You got it champ. Be done today.

**Comment by Miserlou** [comment]
Waiting for Close to document their crappy API..

**Comment by Miserlou** [comment]
Should be fixed, please confirm on the next lead.
