### ISSUE TITLE
skill tags

### ISSUE THREAD

**Issue by libbyroyer** [gundotio/PublicBugs#8]
devs that only want "java" notifications are also getting notifications when "javascript" is tagged. same for "scala" and "scalable"

**Comment by tnewkirk** [comment]
It might just be easiest if there was a way for me to manually remove tags in the job post editor... stuff like 'go' shows up all the time as well.

That way I can get rid of whatever tags aren't relevant to the content.

**Comment by Miserlou** [comment]
Love this one.

**Comment by Miserlou** [comment]
Tags are now a field for the admin job poster, rather than autotags.
